# Generated by Django 6.0.6 on 2026-06-06 15:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Fabric',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=50)),
                ('stock', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Barcode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('roll_no', models.IntegerField()),
                ('machine_no', models.IntegerField()),
                ('meters', models.IntegerField()),
                ('weight', models.IntegerField()),
                ('date', models.DateField(auto_now_add=True)),
                ('dispatched', models.CharField(choices=[('not_dispatched', 'Yet to dispatch'), ('dispatched', 'Dispatched')], default='not_dispatched', max_length=15)),
                ('fabric_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='barcode', to='inventory.fabric')),
            ],
        ),
    ]
