# Generated by Django 6.0.6 on 2026-06-13 06:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Dispatch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dispatch_no', models.CharField(max_length=50, unique=True)),
                ('financial_year', models.CharField(max_length=5)),
                ('sequence_no', models.IntegerField(blank=True, null=True)),
                ('customer_name', models.CharField(max_length=100)),
                ('vehicle_no', models.CharField(max_length=30)),
                ('dispatched_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Fabric',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=50)),
                ('stock', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Roll',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('roll_no', models.CharField(blank=True, null=True, unique=True)),
                ('sequence_no', models.IntegerField(blank=True, null=True)),
                ('machine_no', models.IntegerField()),
                ('meters', models.IntegerField()),
                ('weight', models.IntegerField()),
                ('date', models.DateField(auto_now_add=True)),
                ('dispatch_status', models.CharField(choices=[('not_dispatched', 'Yet to dispatch'), ('dispatched', 'Dispatched')], default='not_dispatched', max_length=15)),
                ('dispatched', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='rolls', to='inventory.dispatch')),
                ('fabric_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rolls', to='inventory.fabric')),
            ],
        ),
        migrations.CreateModel(
            name='Barcode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('barcode', models.CharField(blank=True, max_length=50)),
                ('roll', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='barcode', to='inventory.roll')),
            ],
        ),
    ]
