# Generated by Django 6.0.6 on 2026-06-13 07:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='dispatch',
            name='fabric_type',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.PROTECT, related_name='dispatches', to='inventory.fabric'),
            preserve_default=False,
        ),
    ]
