# Generated by Django 6.0.6 on 2026-06-15 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_dispatch_fabric_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='dispatch',
            name='total_meters',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='dispatch',
            name='total_rolls',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='dispatch',
            name='total_weight',
            field=models.IntegerField(default=0),
        ),
    ]
