# Generated by Django 6.0.6 on 2026-06-10 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0003_alter_barcode_barcode_alter_barcode_fabric_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='barcode',
            name='roll_no',
            field=models.IntegerField(blank=True, null=True, unique=True),
        ),
    ]
