# Generated by Django 6.0.6 on 2026-06-17 05:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0003_dispatch_total_meters_dispatch_total_rolls_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dispatch',
            name='total_weight',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AlterField(
            model_name='roll',
            name='weight',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
