# Generated by Django 6.0.6 on 2026-06-11 18:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0004_alter_barcode_roll_no'),
    ]

    operations = [
        migrations.AddField(
            model_name='barcode',
            name='sequence_no',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
