# Generated by Django 6.0.6 on 2026-06-11 18:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0005_barcode_sequence_no'),
    ]

    operations = [
        migrations.AlterField(
            model_name='barcode',
            name='roll_no',
            field=models.CharField(blank=True, null=True, unique=True),
        ),
    ]
