# Generated by Django 6.0.6 on 2026-06-12 04:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0006_alter_barcode_roll_no'),
    ]

    operations = [
        migrations.AddField(
            model_name='barcode',
            name='firm',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
