# Generated by Django 6.0.6 on 2026-06-12 04:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0007_barcode_firm'),
    ]

    operations = [
        migrations.AlterField(
            model_name='barcode',
            name='firm',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
