# Generated by Django 6.0.6 on 2026-06-12 05:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0008_alter_barcode_firm'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='barcode',
            name='firm',
        ),
    ]
