# Generated by Django 6.0.6 on 2026-06-12 15:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0009_remove_barcode_firm'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='barcode',
            name='date',
        ),
        migrations.RemoveField(
            model_name='barcode',
            name='dispatched',
        ),
        migrations.RemoveField(
            model_name='barcode',
            name='fabric_type',
        ),
        migrations.RemoveField(
            model_name='barcode',
            name='machine_no',
        ),
        migrations.RemoveField(
            model_name='barcode',
            name='meters',
        ),
        migrations.RemoveField(
            model_name='barcode',
            name='sequence_no',
        ),
        migrations.RemoveField(
            model_name='barcode',
            name='weight',
        ),
        migrations.CreateModel(
            name='Roll',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('roll_no', models.CharField(blank=True, null=True, unique=True)),
                ('sequence_no', models.IntegerField(blank=True, null=True)),
                ('machine_no', models.IntegerField()),
                ('meters', models.IntegerField()),
                ('weight', models.IntegerField()),
                ('date', models.DateField(auto_now_add=True)),
                ('dispatched', models.CharField(choices=[('not_dispatched', 'Yet to dispatch'), ('dispatched', 'Dispatched')], default='not_dispatched', max_length=15)),
                ('fabric_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='roll', to='inventory.fabric')),
            ],
        ),
        migrations.AlterField(
            model_name='barcode',
            name='roll_no',
            field=models.OneToOneField(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='barcode', to='inventory.roll'),
            preserve_default=False,
        ),
    ]
