# Generated by Django 6.0.6 on 2026-06-12 15:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0010_remove_barcode_date_remove_barcode_dispatched_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='barcode',
            old_name='roll_no',
            new_name='roll',
        ),
    ]
