# Generated by Django 6.0.6 on 2026-06-12 16:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0011_rename_roll_no_barcode_roll'),
    ]

    operations = [
        migrations.RenameField(
            model_name='barcode',
            old_name='roll',
            new_name='roll_no',
        ),
    ]
