# Generated by Django 6.0.6 on 2026-06-12 16:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0012_rename_roll_barcode_roll_no'),
    ]

    operations = [
        migrations.RenameField(
            model_name='barcode',
            old_name='roll_no',
            new_name='roll',
        ),
    ]
