# Generated by Django 6.0.6 on 2026-06-12 17:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0013_rename_roll_no_barcode_roll'),
    ]

    operations = [
        migrations.CreateModel(
            name='Dispatch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dispatch_no', models.CharField(max_length=50, unique=50)),
                ('customer_name', models.CharField(max_length=100)),
                ('vehicle_no', models.CharField(max_length=30)),
                ('dispatched_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.RenameField(
            model_name='roll',
            old_name='dispatched',
            new_name='dispatch_status',
        ),
        migrations.AlterField(
            model_name='roll',
            name='fabric_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rolls', to='inventory.fabric'),
        ),
        migrations.AddField(
            model_name='roll',
            name='dispatched_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='rolls', to='inventory.dispatch'),
        ),
    ]
